### ISSUE TITLE
byte litteral support for python 3

### ISSUE THREAD

**Issue by JDeVos** [OnroerendErfgoed/skosprovider_rdf#12]
string literals and byte literals are treated indifferently in py2.x but not in py3.x
ex:  str('abc'.encode('utf8')) = 'abc' in py2.x and "b'abc'" in py3.x.

When creating labels, the RDFProvider uses this at https://github.com/OnroerendErfgoed/skosprovider_rdf/blob/master/skosprovider_rdf/providers.py#L143 and therefore produces labels with prefixed strings (ex: b'brief')

**Comment by BartSaelen** [comment]
I hink its better to use the `text_` method from pyramid compat(http://docs.pylonsproject.org/projects/pyramid//en/latest/api/compat.html) or local util like https://github.com/OnroerendErfgoed/oeauth/blob/master/oeauth/compat.py

    str('abc'.encode('utf8'))

should be

    text_('abc'.encode('utf8'))
