### ISSUE TITLE
Unable to install using modern setuptools & pip

### ISSUE THREAD

**Issue by mvaled** [OnroerendErfgoed/skosprovider_rdf#22]
The latest setuptools require (indirectly) the pyparsing package which (seems to) require pyparsing 2.1 (see https://github.com/pypa/packaging/issues/91).

So this makes skosprovider_rdf uninstallable under such environments.

**Comment by mvaled** [comment]
Well I solved by installing setuptools<34.

**Comment by koenedaele** [comment]
pyparsing dependency seems to come from rdflib. 

I just solved this be running `pip install -U setuptools`. That installs the latest setuptools and the latest pyparsing.
